name: sanai3i
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_core: 
  firebase_auth: 
  cloud_firestore: 
  firebase_storage: 
  geoflutterfire: 
  rxdart: 
  provider:
  url_launcher:
  image_picker:
  fluttertoast: 
  qr_flutter: 
  qrscan: 
  google_maps_flutter: 
  location:
  animations: 
  simple_animations: 
  photo_view: 
  cached_network_image: 
  country_code_picker :
  shared_preferences: 
  flutter_verification_code: 
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0


flutter:

  uses-material-design: true

  assets:
    - images/
    - langs/
  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Bold.ttf
          weight: 700
    - family: TajawalRegular
      fonts:
        - asset: fonts/Tajawal-Regular.ttf
          weight: 700